apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-cafe
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      name: azure-cafe
      labels:
        app: azure-cafe
    spec:
      containers:
      - name: azure-cafe
        image: <your Docker Hub ID>/azure-cafe:v1
---
apiVersion: v1
kind: Service
metadata:
  name: azure-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: azure-cafe
